import jsPDF from 'jspdf';

const COLORS = {
  primary: [59, 130, 246],
  dark: [15, 23, 42],
  card: [30, 41, 59],
  text: [241, 245, 249],
  textSecondary: [148, 163, 184],
  textMuted: [100, 116, 139],
  green: [16, 185, 129],
  amber: [245, 158, 11],
  red: [239, 68, 68],
  purple: [139, 92, 246],
  blue: [6, 182, 212],
};

function createPDF(title, orientation = 'portrait') {
  const doc = new jsPDF({ orientation, unit: 'mm', format: 'a4' });
  doc.setFont('helvetica');
  return doc;
}

function addHeader(doc, title, subtitle) {
  const pageWidth = doc.internal.pageSize.getWidth();
  // Header bar
  doc.setFillColor(...COLORS.primary);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 14);
  if (subtitle) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(subtitle, 14, 22);
  }
  // Branding
  doc.setFontSize(8);
  doc.text('AI Readiness Assessment Platform', pageWidth - 14, 14, { align: 'right' });
  doc.text(new Date().toLocaleDateString(), pageWidth - 14, 22, { align: 'right' });
  return 36;
}

function addSectionTitle(doc, y, text, color = COLORS.primary) {
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFillColor(...color);
  doc.rect(14, y - 1, 3, 8, 'F');
  doc.setTextColor(...color);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(text, 20, y + 5);
  doc.setDrawColor(200, 200, 210);
  doc.line(14, y + 9, pageWidth - 14, y + 9);
  return y + 14;
}

function addText(doc, y, text, { size = 10, color = [60, 60, 60], bold = false, maxWidth = 170, indent = 14 } = {}) {
  doc.setFontSize(size);
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setTextColor(...color);
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, indent, y);
  return y + lines.length * (size * 0.45) + 2;
}

function checkPageBreak(doc, y, needed = 30) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - 20) {
    doc.addPage();
    return 20;
  }
  return y;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth / 2, pageHeight - 8, { align: 'center' });
    doc.text('Generated by AI Readiness Assessment Platform', 14, pageHeight - 8);
  }
}

// ============================================================
// Export: Individual Assessment Results
// ============================================================
export function exportResultsPDF(assessment, department, tier, gapAnalysis) {
  const doc = createPDF('Assessment Results');
  let y = addHeader(doc, 'AI Readiness Assessment Results', `${department?.name || ''} — ${assessment.role}`);

  // Score overview
  y = addSectionTitle(doc, y, 'Overall Score');
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.primary);
  doc.text(`${assessment.overallScore}`, 50, y + 14, { align: 'center' });
  doc.setFontSize(12);
  doc.text('/ 100', 66, y + 14);

  doc.setFontSize(16);
  const tierColor = tier?.color ? hexToRgb(tier.color) : COLORS.primary;
  doc.setTextColor(...tierColor);
  doc.text(tier?.name || '', 100, y + 6);
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(tier?.description || '', 100, y + 14);

  y += 22;

  // XP and Badges
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.amber);
  doc.text(`XP: ${assessment.xpTotal || 0}`, 14, y);
  if (assessment.badges?.length) {
    doc.setTextColor(...COLORS.purple);
    doc.text(`Badges: ${assessment.badges.join(', ')}`, 60, y);
  }
  y += 10;

  // Level Scores
  y = addSectionTitle(doc, y, 'Dimension Scores');
  const dimensions = [
    { key: 'awareness', label: 'AI Awareness' },
    { key: 'currentUsage', label: 'Current Usage' },
    { key: 'skillDepth', label: 'Skill Depth' },
    { key: 'strategicThinking', label: 'Strategic Thinking' },
    { key: 'futureReadiness', label: 'Future Readiness' },
    { key: 'technicalFluency', label: 'Technical Fluency' },
  ];

  dimensions.forEach(dim => {
    const score = assessment.scores?.[dim.key] || 0;
    y = checkPageBreak(doc, y, 12);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(dim.label, 14, y);
    doc.text(`${score}%`, 100, y, { align: 'right' });

    // Score bar
    doc.setFillColor(230, 230, 235);
    doc.roundedRect(105, y - 4, 80, 5, 2, 2, 'F');
    const barColor = score >= 70 ? COLORS.green : score >= 40 ? COLORS.amber : COLORS.red;
    doc.setFillColor(...barColor);
    doc.roundedRect(105, y - 4, Math.max(1, (score / 100) * 80), 5, 2, 2, 'F');
    y += 10;
  });

  // Gap Analysis
  if (gapAnalysis) {
    y += 4;
    y = checkPageBreak(doc, y, 40);
    y = addSectionTitle(doc, y, 'North Star Gap Analysis');
    y = addText(doc, y, `Current Maturity: ${gapAnalysis.currentMaturity} / 5.0`, { bold: true, color: [...COLORS.primary] });
    y = addText(doc, y, `Target Maturity: ${gapAnalysis.targetMaturity} / 5.0`, { bold: true, color: [...COLORS.green] });
    const gapColor = gapAnalysis.gapSeverity === 'critical' ? COLORS.red : gapAnalysis.gapSeverity === 'moderate' ? COLORS.amber : COLORS.green;
    y = addText(doc, y, `Gap: ${gapAnalysis.gap} (${gapAnalysis.gapSeverity})`, { bold: true, color: gapColor });
    y += 2;
    y = addText(doc, y, gapAnalysis.transformation, { size: 9, color: [80, 80, 80] });
  }

  // Roadmap
  if (assessment.roadmap) {
    y += 4;
    y = checkPageBreak(doc, y, 30);
    y = addSectionTitle(doc, y, 'Personalized Roadmap');

    const phases = [
      { key: 'thirtyDays', label: '30 Days', color: COLORS.green },
      { key: 'sixtyDays', label: '60-90 Days', color: COLORS.amber },
      { key: 'sixMonths', label: '6 Months', color: COLORS.purple },
    ];

    phases.forEach(phase => {
      const items = assessment.roadmap[phase.key] || [];
      if (items.length === 0) return;
      y = checkPageBreak(doc, y, 20);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...phase.color);
      doc.text(phase.label, 14, y);
      y += 6;
      items.forEach(item => {
        y = checkPageBreak(doc, y, 8);
        y = addText(doc, y, `• ${item}`, { size: 9, color: [80, 80, 80], indent: 18, maxWidth: 165 });
      });
      y += 3;
    });
  }

  addFooter(doc);
  doc.save(`ai-readiness-results-${assessment.department}-${new Date().toISOString().slice(0, 10)}.pdf`);
}

// ============================================================
// Export: Department Explorer
// ============================================================
export function exportDepartmentPDF(dept, classifications, northStarTarget) {
  const doc = createPDF('Department Report');
  let y = addHeader(doc, `${dept.icon} ${dept.name}`, dept.mission);

  // North Star
  if (northStarTarget) {
    y = addSectionTitle(doc, y, `North Star Target: Level ${northStarTarget.level}`);
    y = addText(doc, y, northStarTarget.transformation, { size: 9, color: [80, 80, 80] });
    y += 4;
  }

  // Roles
  y = checkPageBreak(doc, y, 20);
  y = addSectionTitle(doc, y, 'Typical Roles');
  y = addText(doc, y, dept.roles.join(', '), { size: 9, color: [80, 80, 80] });
  y += 4;

  // Metrics
  y = checkPageBreak(doc, y, 20);
  y = addSectionTitle(doc, y, 'Core Metrics');
  y = addText(doc, y, dept.metrics.join(', '), { size: 9, color: [80, 80, 80] });
  y += 4;

  // Activities by classification
  const classOrder = ['humanize', 'agentify', 'automate'];
  const classColors = { humanize: COLORS.green, agentify: COLORS.amber, automate: COLORS.red };
  const classNames = { humanize: 'Humanize', agentify: 'Agentify', automate: 'Automate' };

  classOrder.forEach(cls => {
    const items = dept.activities.filter(a => a.classification === cls);
    if (items.length === 0) return;

    y = checkPageBreak(doc, y, 30);
    y = addSectionTitle(doc, y, `${classNames[cls]} Activities (${items.length})`, classColors[cls]);

    items.forEach(activity => {
      y = checkPageBreak(doc, y, 45);

      // Activity name
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(40, 40, 40);
      doc.text(activity.name, 14, y);
      y += 5;

      // Short description
      y = addText(doc, y, activity.description, { size: 9, color: [80, 80, 80], bold: true });

      // Detailed description
      if (activity.detailedDescription) {
        y = addText(doc, y, activity.detailedDescription, { size: 9, color: [90, 90, 90] });
      }

      // AI Opportunity
      if (activity.aiOpportunity) {
        y = checkPageBreak(doc, y, 15);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(...classColors[cls]);
        doc.text('AI Opportunity:', 18, y);
        y += 4;
        y = addText(doc, y, activity.aiOpportunity, { size: 8, color: [100, 100, 100], indent: 18, maxWidth: 162 });
      }

      // Tools
      if (activity.exampleTools?.length) {
        y = checkPageBreak(doc, y, 10);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        doc.text('Recommended Tools:', 18, y);
        y += 4;
        activity.exampleTools.forEach(tool => {
          y = addText(doc, y, `• ${tool.name} — ${tool.url}`, { size: 8, color: [80, 80, 150], indent: 22, maxWidth: 158 });
        });
      }

      // Implementation Tips
      if (activity.implementationTips?.length) {
        y = checkPageBreak(doc, y, 15);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        doc.text('Implementation Tips:', 18, y);
        y += 4;
        activity.implementationTips.forEach(tip => {
          y = checkPageBreak(doc, y, 8);
          y = addText(doc, y, `• ${tip}`, { size: 8, color: [100, 100, 100], indent: 22, maxWidth: 158 });
        });
      }

      // Maturity Indicators
      if (activity.maturityIndicators) {
        y = checkPageBreak(doc, y, 20);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(60, 60, 60);
        doc.text('Maturity Levels:', 18, y);
        y += 4;
        const mi = activity.maturityIndicators;
        y = addText(doc, y, `Beginner: ${mi.beginner}`, { size: 8, color: [160, 80, 80], indent: 22, maxWidth: 158 });
        y = addText(doc, y, `Intermediate: ${mi.intermediate}`, { size: 8, color: [160, 130, 40], indent: 22, maxWidth: 158 });
        y = addText(doc, y, `Advanced: ${mi.advanced}`, { size: 8, color: [40, 140, 100], indent: 22, maxWidth: 158 });
      }

      // Rationale
      doc.setFontSize(8);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(140, 140, 140);
      y = checkPageBreak(doc, y, 8);
      const rationaleLines = doc.splitTextToSize(`Classification rationale: ${activity.rationale}`, 162);
      doc.text(rationaleLines, 18, y);
      y += rationaleLines.length * 3.5 + 6;
    });
  });

  addFooter(doc);
  doc.save(`department-${dept.id}-ai-classification-report.pdf`);
}

// ============================================================
// Export: Org Dashboard
// ============================================================
export function exportDashboardPDF(assessments, departments, northStarTargets, tierDefinitions) {
  const doc = createPDF('Organization Dashboard', 'landscape');
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = addHeader(doc, 'Organization AI Readiness Dashboard', `${assessments.length} assessments across ${new Set(assessments.map(a => a.department)).size} departments`);

  // Summary stats
  const avgScore = Math.round(assessments.reduce((s, a) => s + a.overallScore, 0) / assessments.length * 10) / 10;
  y = addSectionTitle(doc, y, 'Executive Summary');
  const stats = [
    `Total Assessments: ${assessments.length}`,
    `Average Score: ${avgScore} / 100`,
    `Departments Assessed: ${new Set(assessments.map(a => a.department)).size}`,
    `Date Range: ${new Date(Math.min(...assessments.map(a => new Date(a.timestamp)))).toLocaleDateString()} — ${new Date(Math.max(...assessments.map(a => new Date(a.timestamp)))).toLocaleDateString()}`,
  ];
  stats.forEach(stat => {
    y = addText(doc, y, stat, { size: 10, color: [60, 60, 60] });
  });
  y += 4;

  // Tier Distribution
  y = checkPageBreak(doc, y, 40);
  y = addSectionTitle(doc, y, 'Tier Distribution');
  tierDefinitions.forEach(tier => {
    const count = assessments.filter(a => a.overallScore >= tier.min && a.overallScore <= tier.max).length;
    const rgb = hexToRgb(tier.color);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...rgb);
    doc.text(`${tier.name} (${tier.min}-${tier.max}): ${count} people`, 14, y);
    // Bar
    doc.setFillColor(230, 230, 235);
    doc.roundedRect(120, y - 4, 100, 5, 2, 2, 'F');
    const barWidth = assessments.length > 0 ? (count / assessments.length) * 100 : 0;
    doc.setFillColor(...rgb);
    doc.roundedRect(120, y - 4, Math.max(1, barWidth), 5, 2, 2, 'F');
    y += 8;
  });
  y += 4;

  // Department Scores
  y = checkPageBreak(doc, y, 30);
  y = addSectionTitle(doc, y, 'Department Scores vs. North Star Targets');

  // Table header
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  const cols = [14, 55, 78, 100, 120, 142, 164, 186, 210];
  ['Department', 'Avg', 'Aware', 'Usage', 'Depth', 'Strategy', 'Ready', 'Tech', 'Target'].forEach((h, i) => {
    doc.text(h, cols[i], y);
  });
  y += 2;
  doc.setDrawColor(200, 200, 210);
  doc.line(14, y, pageWidth - 14, y);
  y += 5;

  departments.forEach(dept => {
    const deptAssessments = assessments.filter(a => a.department === dept.id);
    if (deptAssessments.length === 0) return;
    y = checkPageBreak(doc, y, 8);

    const avg = Math.round(deptAssessments.reduce((s, a) => s + a.overallScore, 0) / deptAssessments.length);
    const dimAvg = (key) => Math.round(deptAssessments.reduce((s, a) => s + (a.scores?.[key] || 0), 0) / deptAssessments.length);
    const target = northStarTargets[dept.id]?.level || '-';

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    doc.text(dept.name.slice(0, 18), cols[0], y);
    doc.text(`${avg}`, cols[1], y);
    doc.text(`${dimAvg('awareness')}`, cols[2], y);
    doc.text(`${dimAvg('currentUsage')}`, cols[3], y);
    doc.text(`${dimAvg('skillDepth')}`, cols[4], y);
    doc.text(`${dimAvg('strategicThinking')}`, cols[5], y);
    doc.text(`${dimAvg('futureReadiness')}`, cols[6], y);
    doc.text(`${dimAvg('technicalFluency')}`, cols[7], y);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.green);
    doc.text(`${target}`, cols[8], y);
    y += 7;
  });

  // Individual Assessments
  y += 6;
  y = checkPageBreak(doc, y, 30);
  y = addSectionTitle(doc, y, 'All Individual Assessments');

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(60, 60, 60);
  const aCols = [14, 50, 95, 135, 165, 200, 240];
  ['ID', 'Department', 'Role', 'Score', 'Tier', 'XP', 'Date'].forEach((h, i) => {
    doc.text(h, aCols[i], y);
  });
  y += 2;
  doc.line(14, y, pageWidth - 14, y);
  y += 5;

  assessments.sort((a, b) => new Date(b.timestamp) - new Date(a.timestamp)).forEach(a => {
    y = checkPageBreak(doc, y, 7);
    const dept = departments.find(d => d.id === a.department);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text(a.anonymousId || `#${a.id}`, aCols[0], y);
    doc.text((dept?.name || a.department).slice(0, 20), aCols[1], y);
    doc.text((a.role || '').slice(0, 18), aCols[2], y);
    doc.text(`${a.overallScore}`, aCols[3], y);
    doc.text(a.tier || '', aCols[4], y);
    doc.text(`${a.xpTotal || 0}`, aCols[5], y);
    doc.text(new Date(a.timestamp).toLocaleDateString(), aCols[6], y);
    y += 6;
  });

  addFooter(doc);
  doc.save(`org-ai-readiness-dashboard-${new Date().toISOString().slice(0, 10)}.pdf`);
}

function hexToRgb(hex) {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? [parseInt(result[1], 16), parseInt(result[2], 16), parseInt(result[3], 16)] : [100, 100, 100];
}
